# Generated by Django 4.2.4 on 2023-10-25 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
            preserve_default=False,
        ),
    ]
