# Generated by Django 4.2.4 on 2023-10-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_canalvideo_canaltexto'),
    ]

    operations = [
        migrations.CreateModel(
            name='canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='canalvideo',
            name='comunidad',
        ),
        migrations.DeleteModel(
            name='canalTexto',
        ),
        migrations.DeleteModel(
            name='canalVideo',
        ),
    ]
